INSERT INTO cocktails (name, description, image, price ) VALUES('Whiskey sour', 'Whiskey, sciroppoo di zucchero, succo di limone, albume', 'https://i.pinimg.com/564x/a0/47/3e/a0473e9666f16a3130e2de5e2c78ad60.jpg', 9);
INSERT INTO cocktails (name, description, image, price ) VALUES('Negroni', 'Gin, vermouth rosso, bitter Campari,', 'https://i.pinimg.com/564x/b6/b4/ff/b6b4ffd8f6ceabb5c6b7f1b5886950a8.jpg', 8.50);
INSERT INTO cocktails (name, description, image, price ) VALUES('French 75', 'Gin, champagne, succo di limone,', 'https://i.pinimg.com/564x/5d/83/6e/5d836e013863593f83fdb2359cf315e1.jpg', 10.50);

INSERT INTO categories (nome) VALUES('A base di gin');
INSERT INTO categories (nome) VALUES('A base di Whiskey');
